- name: Setup ansible needed things.
  hosts: all
  gather_facts: no
  tasks:
     - name: "Install Python 3 needed to  run Ansible."
       raw: sudo apt-get update; sudo apt-get -y install python-simplejson

